- name: Run Python script from GitHub
  hosts: localhost
  tasks:
    

    - name: Execute the Python script with the YAML file
      command: python3 ./py_test.py
      register: script_output

    - name: Print the script output
      debug:
        var: script_output.stdout
