- name: App Validation Module
  hosts: all
  tasks:
    - name: Executing App Validation Module
      debug:
        msg: "App Validation Module Completed"

    - name: Python to SQL connection
      debug:
        msg: "Connected successfully"
    
    - name: Execute the Python script with the YAML file
      command: python3 /var/lib/awx/projects/py_mysql/py_sql.py
      register: script_output

    - name: Print the script output
      debug:
        var: script_output.stdout
