- name: App Validation Module
  hosts: all
  tasks:
    - name: Executing App Validation Module
      debug:
        msg: "App Validation Module Completed"

    - name: Execute Python script
      ansible.builtin.script:
        script: |
          #!/usr/bin/env python3
          print ("Hello World!")
    
        # Indicate the interpreter to use for the script
        interpreter: /usr/bin/env python3

      msg: "Connected successfully"
