---
- name: App Validation Module
  hosts: all
  tasks:
    - name: Executing App Validation Module
      debug:
        msg: "App Validation Module Completed"

    - name: Python to SQL connection
      debug:
        msg: "Connected successfully"

    - name: Run a command on remote host
      ansible.builtin.command:
        cmd: "python --version"
